# Default initial positions for Ned's ros2_control fake system

initial_positions:
  gripper::left: 0.0
  gripper::right: 0.0
  joint_1: 0.0
  joint_2: 0.0
  joint_3: 0.0
  joint_4: 0.0
  joint_5: 0.0
  joint_6: 0.0